/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
cuda train torchrec_dlrm                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 231, in load_model
    module = importlib.import_module(c)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/__init__.py", line 7, in <module>
    from .data.dlrm_dataloader import get_dataloader
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/data/dlrm_dataloader.py", line 13, in <module>
    from torchrec.datasets.criteo import (
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/__init__.py", line 10, in <module>
    import torchrec.distributed  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/__init__.py", line 38, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/model_parallel.py", line 26, in <module>
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/__init__.py", line 24, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/planners.py", line 21, in <module>
    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/constants.py", line 12, in <module>
    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/embedding_types.py", line 16, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops_training import EmbeddingLocation
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
    import fbgemm_gpu.docs  # noqa: F401, E402
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/__init__.py", line 9, in <module>
    from . import jagged_tensor_ops, table_batched_embedding_ops  # noqa: F401
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/jagged_tensor_ops.py", line 14, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/_ops.py", line 1125, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train BERT_pytorch                       
run_performance_test(): speedup_experiment == True
0.229x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train Background_Matting                 
run_performance_test(): speedup_experiment == True
0.838x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train DALLE2_pytorch                     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 428, in forward_and_backward_pass
    self.grad_scaler.scale(loss).backward()
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/_tensor.py", line 523, in backward
    torch.autograd.backward(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/autograd/graph.py", line 767, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train LearningToPaint                    
run_performance_test(): speedup_experiment == True
0.503x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train Super_SloMo                        
run_performance_test(): speedup_experiment == True
0.912x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train alexnet                            
run_performance_test(): speedup_experiment == True
0.897x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train basic_gnn_edgecnn                  
run_performance_test(): speedup_experiment == True
0.799x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train basic_gnn_gcn                      
run_performance_test(): speedup_experiment == True
0.749x
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train basic_gnn_gin                      
run_performance_test(): speedup_experiment == True
0.455x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train basic_gnn_sage                     
run_performance_test(): speedup_experiment == True
0.551x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train dcgan                              
run_performance_test(): speedup_experiment == True
0.317x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train demucs                             
run_performance_test(): speedup_experiment == True
0.864x
Op: aten.convolution
Op: aten.addmm
Op: aten.convolution_backward
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train densenet121                        
run_performance_test(): speedup_experiment == True
0.194x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train detectron2_maskrcnn_r_50_c4        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 161, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 472, in forward
    losses = self.losses(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 401, in losses
    storage = get_event_storage()
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/detectron2/utils/events.py", line 34, in get_event_storage
    assert len(
AssertionError: get_event_storage() has to be called inside a 'with EventStorage(...)' context!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train dlrm                               
run_performance_test(): speedup_experiment == True
0.044x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train drq                                
run_performance_test(): speedup_experiment == True
0.364x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train fastNLP_Bert                       
run_performance_test(): speedup_experiment == True
0.633x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train functorch_dp_cifar10               
run_performance_test(): speedup_experiment == True
0.337x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train functorch_maml_omniglot            
run_performance_test(): speedup_experiment == True
0.364x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Albert                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 986, in forward
    outputs = self.albert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 705, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Bart                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1731, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1587, in forward
    decoder_input_ids = shift_tokens_right(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 104, in shift_tokens_right
    shifted_input_ids = input_ids.new_zeros(input_ids.shape)
AttributeError: 'str' object has no attribute 'new_zeros'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Bert                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 961, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Bert_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 961, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_BigBird                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2450, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2026, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_DistilBert                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 905, in forward
    dlbrt_output = self.distilbert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 803, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_GPT2                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_GPT2_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Reformer                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2404, in forward
    reformer_outputs = self.reformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2034, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_T5_base                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_T5_large                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_Whisper                         
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train hf_distil_whisper                  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 296, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/hf_distil_whisper/__init__.py", line 12, in __init__
    raise NotImplementedError("Training is not implemented.")
NotImplementedError: Training is not implemented.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train lennard_jones                      
run_performance_test(): speedup_experiment == True
0.351x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train llava                              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 296, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/llava/__init__.py", line 11, in __init__
    super().__init__(name="llava", test=test, device=device, batch_size=batch_size, extra_args=extra_args)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 32, in __init__
    super().__init__(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 144, in __init__
    self._determine_batch_size(batch_size)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 261, in _determine_batch_size
    raise NotImplementedError(
NotImplementedError: Model's DEFAULT_TRAIN_BSIZE is not implemented.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train maml_omniglot                      
run_performance_test(): speedup_experiment == True
0.367x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train microbench_unbacked_tolist_sum     
run_performance_test(): speedup_experiment == True
0.555x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train mnasnet1_0                         
run_performance_test(): speedup_experiment == True
0.434x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train mobilenet_v2                       
run_performance_test(): speedup_experiment == True
0.723x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train mobilenet_v2_quantized_qat         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 735, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 315, in __call__
    raise e
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 302, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.3", line 207, in forward
    activation_post_process_101 = self.activation_post_process_101(classifier_1);  classifier_1 = None
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/ao/quantization/fake_quantize.py", line 342, in forward
    return torch.fused_moving_avg_obs_fake_quant(
RuntimeError: expected scalar type Float but found Half

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train mobilenet_v3_large                 
run_performance_test(): speedup_experiment == True
0.342x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train moco                               
run_performance_test(): speedup_experiment == True
0.231x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
number of parameters: 123.69M
num decayed parameter tensors: 50, with 124,354,560 parameters
num non-decayed parameter tensors: 98, with 121,344 parameters
using fused AdamW: True
cuda train nanogpt                            
run_performance_test(): speedup_experiment == True
0.377x
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train nvidia_deeprecommender             
run_performance_test(): speedup_experiment == True
1.550x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train opacus_cifar10                     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/opacus/grad_sample/grad_sample_module.py", line 149, in forward
    return self._module(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchvision/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchvision/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1595, in _call_impl
    hook_result = hook(self, args, result)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/opacus/grad_sample/grad_sample_module.py", line 289, in capture_activations_hook
    p._forward_counter += 1
AttributeError: 'Parameter' object has no attribute '_forward_counter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train phlippe_densenet                   
run_performance_test(): speedup_experiment == True
0.273x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train phlippe_resnet                     
run_performance_test(): speedup_experiment == True
0.265x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train pytorch_CycleGAN_and_pix2pix       
run_performance_test(): speedup_experiment == True
0.437x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train pytorch_stargan                    
run_performance_test(): speedup_experiment == True
0.737x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train pytorch_unet                       
run_performance_test(): speedup_experiment == True
0.810x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train resnet152                          
run_performance_test(): speedup_experiment == True
0.469x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train resnet18                           
run_performance_test(): speedup_experiment == True
0.324x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train resnet50                           
run_performance_test(): speedup_experiment == True
0.656x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train resnet50_quantized_qat             
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 735, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 315, in __call__
    raise e
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/fx/graph_module.py", line 302, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.3", line 167, in forward
    activation_post_process_73 = self.activation_post_process_73(fc);  fc = None
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/ao/quantization/fake_quantize.py", line 342, in forward
    return torch.fused_moving_avg_obs_fake_quant(
RuntimeError: expected scalar type Float but found Half

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train resnext50_32x4d                    
run_performance_test(): speedup_experiment == True
0.338x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train sam                                
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 296, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/sam/__init__.py", line 19, in __init__
    super().__init__(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 144, in __init__
    self._determine_batch_size(batch_size)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 261, in _determine_batch_size
    raise NotImplementedError(
NotImplementedError: Model's DEFAULT_TRAIN_BSIZE is not implemented.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train shufflenet_v2_x1_0                 
run_performance_test(): speedup_experiment == True
0.490x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train soft_actor_critic                  
run_performance_test(): speedup_experiment == True
0.495x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train speech_transformer                 
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train squeezenet1_1                      
run_performance_test(): speedup_experiment == True
0.391x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train stable_diffusion_text_encoder      
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train stable_diffusion_unet              
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_efficientnet                  
run_performance_test(): speedup_experiment == True
0.406x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_regnet                        
run_performance_test(): speedup_experiment == True
0.523x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_resnest                       
run_performance_test(): speedup_experiment == True
0.796x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_vision_transformer            
run_performance_test(): speedup_experiment == True
0.348x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_vision_transformer_large      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 652, in forward
    x = self.forward_features(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 640, in forward_features
    x = self.blocks(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 156, in forward
    x = x + self.drop_path2(self.ls2(self.mlp(self.norm2(x))))
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/layers/mlp.py", line 42, in forward
    x = self.fc1(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 0 has a total capacity of 19.50 GiB of which 25.94 MiB is free. Including non-PyTorch memory, this process has 19.43 GiB memory in use. Of the allocated memory 19.20 GiB is allocated by PyTorch, and 7.33 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train timm_vovnet                        
run_performance_test(): speedup_experiment == True
0.503x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train torch_multimodal_clip              
run_performance_test(): speedup_experiment == True
0.427x
Op: aten.convolution
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train tts_angular                        
run_performance_test(): speedup_experiment == True
0.904x
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train vgg16                              
run_performance_test(): speedup_experiment == True
0.868x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train vision_maskrcnn                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 426, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchvision/torchvision/models/detection/generalized_rcnn.py", line 62, in forward
    torch._assert(False, "targets should not be none when in training mode")
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/__init__.py", line 1571, in _assert
    assert condition, message
AssertionError: targets should not be none when in training mode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda train yolov3                             
run_performance_test(): speedup_experiment == True
0.347x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
speedup             gmean=0.00x mean=0.359x
abs_latency         gmean=0.00x mean=63.144x
compilation_latency mean=58.685 seconds
compression_ratio   mean=0.445x
eager_peak_mem      gmean=0.00x mean=1.200x
dynamo_peak_mem     gmean=0.00x mean=1.626x
calls_captured      gmean=0.00x mean=249.507x
unique_graphs       gmean=0.00x mean=2.275x
graph_breaks        gmean=0.00x mean=5.667x
unique_graph_breaks gmean=0.00x mean=4.217x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=0.000x
Finished torchbench-------------------
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train adv_inception_v3                   
run_performance_test(): speedup_experiment == True
0.789x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train beit_base_patch16_224              
run_performance_test(): speedup_experiment == True
0.781x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_efficient_attention
Op: aten.mm
Op: aten._scaled_dot_product_efficient_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train botnet26t_256                      
run_performance_test(): speedup_experiment == True
0.611x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train cait_m36_384                       
run_performance_test(): speedup_experiment == True
0.822x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train coat_lite_mini                     
run_performance_test(): speedup_experiment == True
0.759x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train convit_base                        
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train convmixer_768_32                   
run_performance_test(): speedup_experiment == True
0.881x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train convnext_base                      
run_performance_test(): speedup_experiment == True
0.696x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train crossvit_9_240                     
run_performance_test(): speedup_experiment == True
0.713x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.bmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train cspdarknet53                       
run_performance_test(): speedup_experiment == True
0.693x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train deit_base_distilled_patch16_224    
run_performance_test(): speedup_experiment == True
0.743x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train dla102                             
run_performance_test(): speedup_experiment == True
0.752x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train dm_nfnet_f0                        
run_performance_test(): speedup_experiment == True
0.857x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train dpn107                             
run_performance_test(): speedup_experiment == True
0.707x
Op: aten.convolution
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train eca_botnext26ts_256                
run_performance_test(): speedup_experiment == True
0.629x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train eca_halonext26ts                   
run_performance_test(): speedup_experiment == True
0.637x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train ese_vovnet19b_dw                   
run_performance_test(): speedup_experiment == True
0.663x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train fbnetc_100                         
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train fbnetv3_b                          
run_performance_test(): speedup_experiment == True
0.769x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train gernet_l                           
run_performance_test(): speedup_experiment == True
0.630x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train ghostnet_100                       
run_performance_test(): speedup_experiment == True
0.819x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train gluon_inception_v3                 
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train gmixer_24_224                      
run_performance_test(): speedup_experiment == True
0.745x
Op: aten.convolution
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train gmlp_s16_224                       
run_performance_test(): speedup_experiment == True
0.744x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train hrnet_w18                          
run_performance_test(): speedup_experiment == True
0.667x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train inception_v3                       
run_performance_test(): speedup_experiment == True
0.798x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train jx_nest_base                       
run_performance_test(): speedup_experiment == True
0.780x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train lcnet_050                          
run_performance_test(): speedup_experiment == True
0.787x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train levit_128                          
run_performance_test(): speedup_experiment == True
0.661x
Op: aten.convolution
Op: aten.mm
Op: aten.bmm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mixer_b16_224                      
run_performance_test(): speedup_experiment == True
0.713x
Op: aten.convolution
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mixnet_l                           
run_performance_test(): speedup_experiment == True
0.843x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mnasnet_100                        
run_performance_test(): speedup_experiment == True
0.716x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mobilenetv2_100                    
run_performance_test(): speedup_experiment == True
0.711x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mobilenetv3_large_100              
run_performance_test(): speedup_experiment == True
0.744x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train mobilevit_s                        
run_performance_test(): speedup_experiment == True
0.657x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten.convolution_backward
Op: aten._scaled_dot_product_flash_attention_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train nfnet_l0                           
run_performance_test(): speedup_experiment == True
0.805x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train pit_b_224                          
run_performance_test(): speedup_experiment == True
0.753x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train pnasnet5large                      
run_performance_test(): speedup_experiment == True
0.670x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train poolformer_m36                     
run_performance_test(): speedup_experiment == True
0.706x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train regnety_002                        
run_performance_test(): speedup_experiment == True
0.698x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train repvgg_a2                          
run_performance_test(): speedup_experiment == True
0.657x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train res2net101_26w_4s                  
run_performance_test(): speedup_experiment == True
0.782x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train res2net50_14w_8s                   
run_performance_test(): speedup_experiment == True
0.790x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train res2next50                         
run_performance_test(): speedup_experiment == True
0.775x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train resmlp_12_224                      
run_performance_test(): speedup_experiment == True
0.717x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train resnest101e                        
run_performance_test(): speedup_experiment == True
0.747x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train rexnet_100                         
run_performance_test(): speedup_experiment == True
0.756x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train sebotnet33ts_256                   
run_performance_test(): speedup_experiment == True
0.695x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train selecsls42b                        
run_performance_test(): speedup_experiment == True
1.490x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train spnasnet_100                       
run_performance_test(): speedup_experiment == True
0.713x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train swin_base_patch4_window7_224       
run_performance_test(): speedup_experiment == True
0.513x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train swsl_resnext101_32x16d             
run_performance_test(): speedup_experiment == True
0.741x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train tf_efficientnet_b0                 
run_performance_test(): speedup_experiment == True
0.753x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train tf_mixnet_l                        
run_performance_test(): speedup_experiment == True
0.841x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train tinynet_a                          
run_performance_test(): speedup_experiment == True
0.708x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train tnt_s_patch16_224                  
run_performance_test(): speedup_experiment == True
0.812x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.bmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train twins_pcpvt_base                   
run_performance_test(): speedup_experiment == True
0.710x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train visformer_small                    
run_performance_test(): speedup_experiment == True
0.769x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
Op: aten.mm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train vit_base_patch16_224               
run_performance_test(): speedup_experiment == True
0.743x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train volo_d1_224                        
run_performance_test(): speedup_experiment == True
0.815x
Op: aten.convolution
Op: aten.mm
Op: aten.addmm
Op: aten.bmm
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
cuda train xcit_large_24_p8_224               
run_performance_test(): speedup_experiment == True
0.829x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
Op: aten._scaled_dot_product_flash_attention_backward
Op: aten.convolution_backward
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/timm
speedup             gmean=0.74x mean=0.750x
abs_latency         gmean=340.89x mean=376.213x
compilation_latency mean=176.417 seconds
compression_ratio   mean=1.110x
eager_peak_mem      gmean=7.98x mean=8.596x
dynamo_peak_mem     gmean=7.25x mean=7.808x
calls_captured      gmean=851.29x mean=1000.810x
unique_graphs       gmean=2.63x mean=2.690x
graph_breaks        gmean=7.54x mean=7.569x
unique_graph_breaks gmean=5.94x mean=5.948x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=0.000x
Finished timm-------------------
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train AlbertForMaskedLM                  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train AlbertForQuestionAnswering         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train AllenaiLongformerBase              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BartForCausalLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BartForConditionalGeneration       
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BertForMaskedLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BertForQuestionAnswering           
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BlenderbotForCausalLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BlenderbotSmallForCausalLM         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train BlenderbotSmallForConditionalGeneration 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train CamemBert                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DebertaForMaskedLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DebertaForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DebertaV2ForMaskedLM               
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DebertaV2ForQuestionAnswering      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DistilBertForMaskedLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DistilBertForQuestionAnswering     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train DistillGPT2                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train ElectraForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train ElectraForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train GPT2ForSequenceClassification      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train GoogleFnet                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train LayoutLMForMaskedLM                
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train LayoutLMForSequenceClassification  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train M2M100ForConditionalGeneration     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MBartForCausalLM                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MBartForConditionalGeneration      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MT5ForConditionalGeneration        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MegatronBertForCausalLM            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MegatronBertForQuestionAnswering   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MobileBertForMaskedLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train MobileBertForQuestionAnswering     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train OPTForCausalLM                     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train PLBartForCausalLM                  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train PLBartForConditionalGeneration     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train PegasusForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train PegasusForConditionalGeneration    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train RobertaForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train RobertaForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train Speech2Text2ForCausalLM            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train T5ForConditionalGeneration         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train T5Small                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train TrOCRForCausalLM                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train XGLMForCausalLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train XLNetLMHeadModel                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
cuda train YituTechConvBert                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/huggingface
speedup     gmean=0.00x mean=0.000x
abs_latency gmean=0.00x mean=0.000x
Starting eval suite------------------
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
cuda eval  torchrec_dlrm                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 231, in load_model
    module = importlib.import_module(c)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/__init__.py", line 7, in <module>
    from .data.dlrm_dataloader import get_dataloader
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/data/dlrm_dataloader.py", line 13, in <module>
    from torchrec.datasets.criteo import (
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/__init__.py", line 10, in <module>
    import torchrec.distributed  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/__init__.py", line 38, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/model_parallel.py", line 26, in <module>
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/__init__.py", line 24, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/planners.py", line 21, in <module>
    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/constants.py", line 12, in <module>
    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/embedding_types.py", line 16, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops_training import EmbeddingLocation
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
    import fbgemm_gpu.docs  # noqa: F401, E402
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/__init__.py", line 9, in <module>
    from . import jagged_tensor_ops, table_batched_embedding_ops  # noqa: F401
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/jagged_tensor_ops.py", line 14, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/_ops.py", line 1125, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  BERT_pytorch                       
run_performance_test(): speedup_experiment == True
0.248x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  Background_Matting                 
run_performance_test(): speedup_experiment == True
0.564x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  DALLE2_pytorch                     
run_performance_test(): speedup_experiment == True
0.215x
Op: aten.addmm
Op: aten._scaled_dot_product_efficient_attention
Op: aten.mm
Op: aten.bmm
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  LearningToPaint                    
run_performance_test(): speedup_experiment == True
0.340x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  Super_SloMo                        
run_performance_test(): speedup_experiment == True
0.763x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  alexnet                            
run_performance_test(): speedup_experiment == True
0.768x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  basic_gnn_edgecnn                  
run_performance_test(): speedup_experiment == True
0.596x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  basic_gnn_gcn                      
run_performance_test(): speedup_experiment == True
0.635x
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  basic_gnn_gin                      
run_performance_test(): speedup_experiment == True
0.314x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  basic_gnn_sage                     
run_performance_test(): speedup_experiment == True
0.374x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  cm3leon_generate                   
run_performance_test(): speedup_experiment == True
0.113x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  dcgan                              
run_performance_test(): speedup_experiment == True
0.527x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  demucs                             
run_performance_test(): speedup_experiment == True
0.736x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  densenet121                        
run_performance_test(): speedup_experiment == True
0.342x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_c4     
run_performance_test(): speedup_experiment == True
0.154x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_dc5    
run_performance_test(): speedup_experiment == True
0.413x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_fpn    
run_performance_test(): speedup_experiment == True
0.292x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_c4      
run_performance_test(): speedup_experiment == True
0.596x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_dc5     
run_performance_test(): speedup_experiment == True
0.528x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_fpn     
run_performance_test(): speedup_experiment == True
0.449x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_fcos_r_50_fpn           
run_performance_test(): speedup_experiment == True
0.241x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_maskrcnn_r_101_c4       
run_performance_test(): speedup_experiment == True
0.509x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_maskrcnn_r_101_fpn      
run_performance_test(): speedup_experiment == True
0.308x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_maskrcnn_r_50_c4        
run_performance_test(): speedup_experiment == True
0.584x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  detectron2_maskrcnn_r_50_fpn       
run_performance_test(): speedup_experiment == True
0.400x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  dlrm                               
run_performance_test(): speedup_experiment == True
0.416x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  doctr_det_predictor                
run_performance_test(): speedup_experiment == True
0.417x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  doctr_reco_predictor               
run_performance_test(): speedup_experiment == True
0.234x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  drq                                
run_performance_test(): speedup_experiment == True
0.254x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  fastNLP_Bert                       
run_performance_test(): speedup_experiment == True
0.035x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  functorch_dp_cifar10               
run_performance_test(): speedup_experiment == True
0.182x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  functorch_maml_omniglot            
run_performance_test(): speedup_experiment == True
0.219x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Albert                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 986, in forward
    outputs = self.albert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 704, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Bart                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1731, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1587, in forward
    decoder_input_ids = shift_tokens_right(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 104, in shift_tokens_right
    shifted_input_ids = input_ids.new_zeros(input_ids.shape)
AttributeError: 'str' object has no attribute 'new_zeros'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Bert                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 960, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Bert_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 960, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_BigBird                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2450, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2025, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_DistilBert                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 905, in forward
    dlbrt_output = self.distilbert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 802, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_GPT2                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_GPT2_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Reformer                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2404, in forward
    reformer_outputs = self.reformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2034, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_T5                              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_T5_base                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_T5_generate                     
run_performance_test(): speedup_experiment == True
0.161x
Op: aten.mm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_T5_large                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_Whisper                         
run_performance_test(): speedup_experiment == True
0.564x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  hf_distil_whisper                  
run_performance_test(): speedup_experiment == True
0.313x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  lennard_jones                      
run_performance_test(): speedup_experiment == True
0.191x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  llama                              
run_performance_test(): speedup_experiment == True
0.271x
Op: aten.mm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  llama_v2_7b_16h                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1168, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 966, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/functional.py", line 2266, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  llava                              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 303, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/llava/__init__.py", line 11, in __init__
    super().__init__(name="llava", test=test, device=device, batch_size=batch_size, extra_args=extra_args)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 53, in __init__
    self.model = self.model.to(self.device)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2556, in to
    return super().to(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacity of 19.50 GiB of which 43.94 MiB is free. Including non-PyTorch memory, this process has 19.41 GiB memory in use. Of the allocated memory 19.23 GiB is allocated by PyTorch, and 17.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  maml                               
run_performance_test(): speedup_experiment == True
cuda eval  maml_omniglot                      
run_performance_test(): speedup_experiment == True
0.228x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.convolution
Op: aten.addmm
cuda eval  microbench_unbacked_tolist_sum     
run_performance_test(): speedup_experiment == True
0.550x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  mnasnet1_0                         
run_performance_test(): speedup_experiment == True
0.155x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.convolution
Op: aten.addmm
cuda eval  mobilenet_v2                       
run_performance_test(): speedup_experiment == True
0.121x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.convolution
Op: aten.addmm
cuda eval  mobilenet_v2_quantized_qat         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 303, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/mobilenet_v2_quantized_qat/__init__.py", line 21, in __init__
    raise NotImplementedError("The eval test only supports CPU.")
NotImplementedError: The eval test only supports CPU.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
cuda eval  mobilenet_v3_large                 
run_performance_test(): speedup_experiment == True
0.112x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.convolution
Op: aten.addmm
cuda eval  moco                               
run_performance_test(): speedup_experiment == True
0.219x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
cuda eval  moondream                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/phi/modeling_phi.py", line 1046, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/phi/modeling_phi.py", line 861, in forward
    batch_size, seq_length = input_ids.shape[:2]
AttributeError: 'str' object has no attribute 'shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
number of parameters: 123.69M
num decayed parameter tensors: 50, with 124,354,560 parameters
num non-decayed parameter tensors: 98, with 121,344 parameters
using fused AdamW: True
cuda eval  nanogpt                            
run_performance_test(): speedup_experiment == True
0.163x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
cuda eval  nvidia_deeprecommender             
run_performance_test(): speedup_experiment == True
0.877x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/models/torchbench
Op: aten.addmm
cuda eval  opacus_cifar10                     
